namespace SQliteOrm;

/// <summary>Marks an integer primary key as generated by SQLite AUTOINCREMENT.</summary>
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
public sealed class AutoIncrementAttribute : Attribute
{
}
