using System.Reflection;

namespace SQliteOrm.Mapping;

internal sealed class PropertyMap
{
    internal PropertyMap(PropertyInfo property, string columnName, string sqliteType, bool isNullable,
        bool isPrimaryKey, bool isDatabaseGenerated, bool isAutoIncrement, bool isUnique, bool isRequired,
        ForeignKeyAttribute? foreignKey)
    {
        Property = property; ColumnName = columnName; SqliteType = sqliteType; IsNullable = isNullable;
        IsPrimaryKey = isPrimaryKey; IsDatabaseGenerated = isDatabaseGenerated;
        IsAutoIncrement = isAutoIncrement; IsUnique = isUnique;
        IsRequired = isRequired; ForeignKey = foreignKey;
    }
    internal PropertyInfo Property { get; }
    internal string PropertyName => Property.Name;
    internal string ColumnName { get; }
    internal Type ClrType => Property.PropertyType;
    internal string SqliteType { get; }
    internal bool IsNullable { get; }
    internal bool IsPrimaryKey { get; }
    internal bool IsDatabaseGenerated { get; }
    internal bool IsAutoGenerated => IsDatabaseGenerated;
    internal bool IsAutoIncrement { get; }
    internal bool IsUnique { get; }
    internal bool IsRequired { get; }
    internal ForeignKeyAttribute? ForeignKey { get; }
    internal bool CanWrite => Property.CanWrite;
    internal object? GetValue(object instance) => Property.GetValue(instance);
    internal void SetValue(object instance, object? value) => Property.SetValue(instance, value);
}
